### ISSUE TITLE
URL Bar that doesn't work

### ISSUE THREAD

**Issue by DBSuwu** [Shina-SG/Shina-Fox#21]
I did everything according to the instructions, but still does not come out (even reset configs)

https://github.com/Shina-SG/Shina-Fox/assets/70775103/a3add21c-cff7-400e-ae27-b964abdce970

**Comment by Shina-SG** [comment]
Get the latest userChrome.css and replace it in the chrome folder https://github.com/Shina-SG/Shina-Fox/blob/main/userChrome.css and currently firefox keep having weird experiments and bugs on their beta/developer/nighty branch while I'm busy with making version 0.2 of Shina Fox, so can't do much for now

**Comment by Shina-SG** [comment]
Stable Firefox still work fine but if anyone want to try debug or fix this them-self while I'm busy, what you want to do is:
1. How to enable live debugging for userChrome.css
2. In the Inspector, search for the id `urlbar` the problem is in there
3. The code that make the whole animation in my userChrome.css is at line 571 to 618
4. Since the Stable and the ESR is working fine, I suggest compare Stable/ESR to Beta/Dev/Nightly side by side with live debugging, find the difference and add correction to fixes the difference

**Comment by Shina-SG** [comment]
Ok I think I found the problem `browser.urlbar.suggest.topsites` have to be `true` in `about:config` + the latest userChrome.css then it should be fine for Beta/Dev/Nightly since for some reason on some people firefox `browser.urlbar.suggest.topsites` is set to `false`

**Comment by DBSuwu** [comment]
1. The file you threw at me didn't help me at all

2. _browser.urlbar.suggest.topsites_ was set to **true** from the beginning and that didn't help either.

I will wait for version 0.2 and see if it worked or not.

**Comment by Shina-SG** [comment]
lastly try with `keepPanelOpenDuringImeComposition` set to `true` since aside from this I can't reproduce it anywhere

**Comment by DBSuwu** [comment]
I think the problem is in firefox itself or in my crooked hands, pure firefox works without problems but when I do account synchronization the url-bar instantly crashes, how to solve I don't know. Switched to librewolf as it works well for me

**Comment by DBSuwu** [comment]
Anyway, the problem was account synchronization, something I did that url-bar just broke. Had to do it all over again. I'm really sorry for my crooked hands that I made you suffer
